DELETE http://localhost:3001/api/persons/

###
GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/61c8229c9693b33eea0070e9

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Baboucarr Sallah",
    "number": 729874363
}

###
PUT http://localhost:3001/api/persons/61c8229c9693b33eea0070e9
Content-Type: application/json

{
    "name": "Baboucarr Sallah",
    "number": 4746521433
}

###
requests for to the heroku server on the internet.

###
POST https://secret-tundra-98217.herokuapp.com/api/persons
Content-Type: application/json

{
    "name": "Baboucarr Sallah",
    "number": 729874363
}

###
GET https://secret-tundra-98217.herokuapp.com/api/persons

###
GET https://secret-tundra-98217.herokuapp.com/api/persons/2